// <auto-generated />
using MedFiszkiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedFiszkiApi.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221022102108_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("MedFiszkiApi.Entities.AnatomyTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InPolish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Portion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnatomyTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
